language: ruby
rvm:
  - jruby-19mode
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec --color --format documentation
before_script:
  - cp config/database.example.yml config/database.yml
  - mysql -e "create database grossman_test"
  - mysql -e "create database gman_services_test"
before_install:
  - export JRUBY_OPTS='--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -Xcext.enabled=false -J-Xss2m -Xcompile.invokedynamic=false'
