octopus:
  environments:
    - development
    - production
    - test
  development:
    grossman:
      adapter: sqlite3
      database: grossman

    gman_services:
      adapter: sqlite3
      database: db/gman_services.sqlite3

  production:
    grossman:
      adapter: sqlite3
      database: grossman

    gman_services:
      adapter: sqlite3
      database: db/gman_services.sqlite3

  test:
    grossman:
      adapter: sqlite3
      database: grossman

    gman_services:
      adapter: sqlite3
      database: db/gman_services.sqlite3

default_migration_group: gman_services
